### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by yumusb** [syyu6/WinRpcTest#2]
你好，
刚看了一下该项目具体代码实现，是通过 
        elif "0x709" in str(err):
            print("[+] " + str(ip).ljust(15), "-> ", "Internet Accessible !!!")
和DNSlog中是否有记录
来双重校验判断网络是否畅通，我不仅有如下疑问：

仅靠第一处则可以判断DNS、HTTP均出网；
仅靠第二处则可以判断DNS出网；
但是在真实的环境中，这两者的结果可能不会相同。

所以不如直接连通baidu.com 或者 http://www.msftconnecttest.com/ 进行测试，并且减少了DNSLOG暴露的风险。

**Comment by syyu6** [comment]
你好，是这样的，返回Error Code “0x709”仅能表示已经成功发送请求，并不能代表网络畅通，无论机器出网或不出网，报错内容均为"0x709"，所以需要用到dnslog获取到发送的具体值（即发送时填充的IP）。
输出“Internet Accessible !!!”，是来提交PR的师傅修改的，原本输出内容为“Send Done!”，这个可以在之前的版本中看到。
这里确实可能会产生误解，后续我会将输出内容修改回去的。
能够出网的机器会在最后的[+]success ips中体现，或者使用 -o 参数保存到文件。

感谢您的Issues。

**Comment by yumusb** [comment]
那 可能需要 http log   ┑(￣Д ￣)┍

**Comment by syyu6** [comment]
是的，关于DNS、HTTP是否均出网的问题，还在修改中，后续应该会完善的。
